apiVersion: v3.1.0
kind: DataContract
id: 8460a400-04e8-4b17-992d-b4d025557b4a
version: 1.0.0
status: active
name: supplies
description:
  purpose: Supply dimension table with cost and perishability info
schema:
  - name: supplies
    description: Supply dimension table with cost and perishability info
    logicalType: object
    properties:
      - name: supply_id
        description: Unique supply record identifier
        logicalType: string
        physicalType: STRING
        required: true
        primaryKey: true
      - name: supply_name
        description: Supply item name
        logicalType: string
        physicalType: STRING
        required: true
      - name: product_id
        description: Product identifier (FK to products dimension)
        logicalType: string
        physicalType: STRING
        required: true
      - name: supply_cost
        description: Supply cost in dollars
        logicalType: string
        physicalType: NUMBER
        required: false
      - name: is_perishable
        description: Whether supply is perishable
        logicalType: boolean
        physicalType: BOOLEAN
        required: false
customProperties:
  - property: tableIndex
    value: '0'
  - property: apiVersion
    value: v3.1.0
  - property: version
    value: 1.0.0
  - property: status
    value: active
  - property: kind
    value: DataContract
  - property: odcsMetadata
    value: '[object Object]'
  - property: customProperties
    value: '[object Object]'
  - property: system_id
    value: ad789620-a825-4bc4-afd7-429db96a6359
tags:
  - mart
  - supplies
  - dimension
  - dm_level:Gold
