apiVersion: v3.1.0
kind: DataContract
id: a1b365b7-9562-4036-85e5-032324ca59a2
version: 1.0.0
status: active
name: customers
description:
  purpose: Customer dimension table with lifetime metrics and segmentation
schema:
  - name: customers
    description: Customer dimension table with lifetime metrics and segmentation
    logicalType: object
    properties:
      - name: customer_id
        description: Unique customer identifier
        logicalType: integer
        physicalType: INTEGER
        required: true
        primaryKey: true
      - name: customer_name
        description: Customer full name
        logicalType: string
        physicalType: STRING
        required: true
      - name: first_order_date
        description: Date of customer first order
        logicalType: date
        physicalType: DATE
        required: false
      - name: most_recent_order_date
        description: Date of customer most recent order
        logicalType: date
        physicalType: DATE
        required: false
      - name: lifetime_order_count
        description: Total number of orders placed
        logicalType: integer
        physicalType: INTEGER
        required: false
      - name: lifetime_order_value
        description: Total value of all orders in dollars
        logicalType: string
        physicalType: NUMBER
        required: false
customProperties:
  - property: tableIndex
    value: '0'
  - property: apiVersion
    value: v3.1.0
  - property: version
    value: 1.0.0
  - property: status
    value: active
  - property: kind
    value: DataContract
  - property: odcsMetadata
    value: '[object Object]'
  - property: customProperties
    value: '[object Object]'
  - property: system_id
    value: ad789620-a825-4bc4-afd7-429db96a6359
tags:
  - mart
  - customers
  - dimension
  - dm_level:Gold
