apiVersion: v3.1.0
kind: DataContract
id: 2d2cd506-372f-48a0-a880-a7399d8208a5
version: 1.0.0
status: active
name: locations
description:
  purpose: Location dimension table with store information
schema:
  - name: locations
    description: Location dimension table with store information
    logicalType: object
    properties:
      - name: location_id
        description: Unique location identifier
        logicalType: string
        physicalType: STRING
        required: true
        primaryKey: true
      - name: location_name
        description: Location display name
        logicalType: string
        physicalType: STRING
        required: true
      - name: opened_date
        description: Date location opened
        logicalType: date
        physicalType: DATE
        required: false
      - name: tax_rate
        description: Location tax rate
        logicalType: string
        physicalType: NUMBER
        required: false
customProperties:
  - property: tableIndex
    value: '0'
  - property: apiVersion
    value: v3.1.0
  - property: version
    value: 1.0.0
  - property: status
    value: active
  - property: kind
    value: DataContract
  - property: odcsMetadata
    value: '[object Object]'
  - property: customProperties
    value: '[object Object]'
  - property: system_id
    value: ad789620-a825-4bc4-afd7-429db96a6359
tags:
  - mart
  - locations
  - dimension
  - dm_level:Gold
