apiVersion: v3.1.0
kind: DataContract
id: 9931fece-ad3b-46ad-8872-10ae4327501a
version: 1.0.0
status: active
name: stg_locations
description:
  purpose: Staged store location data with standardized attributes
schema:
  - name: stg_locations
    description: Staged store location data with standardized attributes
    logicalType: object
    properties:
      - name: location_id
        description: Standardized location identifier
        logicalType: string
        physicalType: STRING
        required: true
        primaryKey: true
      - name: location_name
        description: Location display name
        logicalType: string
        physicalType: STRING
        required: true
      - name: opened_date
        description: Date location opened
        logicalType: date
        physicalType: DATE
        required: false
      - name: tax_rate
        description: Location tax rate as decimal
        logicalType: string
        physicalType: NUMBER
        required: false
customProperties:
  - property: tableIndex
    value: '0'
  - property: apiVersion
    value: v3.1.0
  - property: version
    value: 1.0.0
  - property: status
    value: active
  - property: kind
    value: DataContract
  - property: odcsMetadata
    value: '[object Object]'
  - property: customProperties
    value: '[object Object]'
  - property: system_id
    value: ad789620-a825-4bc4-afd7-429db96a6359
tags:
  - staging
  - locations
  - dm_level:Silver
